# Generated by Django 5.1.7 on 2025-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_alter_model_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
